import React from 'react';
import { 
  Award, 
  Clock, 
  CheckCircle, 
  Target,
  Zap,
  BarChart3,
  Download,
} from 'lucide-react';

const InterviewReport = ({ candidate, onClose, onViewDashboard }) => {
  const totalScore = candidate.answers.reduce((sum, ans) => sum + ans.score, 0);
  const maxScore = candidate.answers.reduce((sum, ans) => {
    const max = ans.difficulty === 'Easy' ? 10 : ans.difficulty === 'Medium' ? 20 : 30;
    return sum + max;
  }, 0);
  const percentage = Math.round((totalScore / maxScore) * 100);
  
  const totalTimeUsed = candidate.answers.reduce((sum, ans) => sum + ans.timeUsed, 0);
  const avgTimePerQuestion = Math.round(totalTimeUsed / candidate.answers.length);

  // Calculate performance rating
  let performanceRating = '';
  let ratingColor = '';
  let ratingBg = '';
  
  if (percentage >= 90) {
    performanceRating = 'Outstanding';
    ratingColor = 'text-green-600';
    ratingBg = 'bg-green-50 border-green-200';
  } else if (percentage >= 80) {
    performanceRating = 'Excellent';
    ratingColor = 'text-blue-600';
    ratingBg = 'bg-blue-50 border-blue-200';
  } else if (percentage >= 70) {
    performanceRating = 'Good';
    ratingColor = 'text-indigo-600';
    ratingBg = 'bg-indigo-50 border-indigo-200';
  } else if (percentage >= 60) {
    performanceRating = 'Average';
    ratingColor = 'text-yellow-600';
    ratingBg = 'bg-yellow-50 border-yellow-200';
  } else {
    performanceRating = 'Needs Improvement';
    ratingColor = 'text-red-600';
    ratingBg = 'bg-red-50 border-red-200';
  }

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  const handleDownloadReport = () => {
    const reportText = `
INTERVIEW REPORT
================

Candidate: ${candidate.name}
Email: ${candidate.email}
Date: ${new Date(candidate.completedAt).toLocaleString()}

OVERALL PERFORMANCE
-------------------
Score: ${totalScore}/${maxScore} (${percentage}%)
Rating: ${performanceRating}
Questions Answered: ${candidate.answers.length}
Total Time: ${formatTime(totalTimeUsed)}

QUESTION-BY-QUESTION BREAKDOWN
------------------------------
${candidate.answers.map((ans, idx) => `
Question ${idx + 1} (${ans.difficulty}):
${ans.question}

Answer:
${ans.answer}

Score: ${ans.score}
Time: ${formatTime(ans.timeUsed)}
Feedback: ${ans.feedback || 'N/A'}
`).join('\n---\n')}

Generated by AI Interview Assistant
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Interview_Report_${candidate.name}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-4xl w-full my-8 shadow-2xl">
        {/* Header */}
        <div className="bg-gradient-to-r from-indigo-600 to-purple-600 px-6 py-8 rounded-t-2xl">
          <div className="text-center text-white">
            <div className="flex justify-center mb-4">
              <div className="bg-white bg-opacity-20 p-4 rounded-full backdrop-blur-sm">
                <Award className="w-12 h-12" />
              </div>
            </div>
            <h1 className="text-3xl font-bold mb-2">Interview Complete! 🎉</h1>
            <p className="text-indigo-100 text-lg">Here's your performance report</p>
          </div>
        </div>

        <div className="p-6 md:p-8">
          {/* Candidate Info */}
          <div className="bg-gray-50 rounded-xl p-6 mb-6">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div>
                <h2 className="text-2xl font-bold text-gray-800">{candidate.name}</h2>
                <p className="text-gray-600">{candidate.email}</p>
                <p className="text-sm text-gray-500 mt-1">
                  {new Date(candidate.completedAt).toLocaleString()}
                </p>
              </div>
              <div className={`px-6 py-3 rounded-xl border-2 ${ratingBg}`}>
                <div className={`text-3xl font-bold ${ratingColor} text-center`}>
                  {percentage}%
                </div>
                <div className={`text-sm font-semibold ${ratingColor} text-center mt-1`}>
                  {performanceRating}
                </div>
              </div>
            </div>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl p-4 border border-blue-200">
              <div className="flex items-center gap-3">
                <div className="bg-blue-500 p-2 rounded-lg">
                  <Target className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="text-sm text-blue-700 font-medium">Total Score</p>
                  <p className="text-2xl font-bold text-blue-900">{totalScore}/{maxScore}</p>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-xl p-4 border border-green-200">
              <div className="flex items-center gap-3">
                <div className="bg-green-500 p-2 rounded-lg">
                  <CheckCircle className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="text-sm text-green-700 font-medium">Questions</p>
                  <p className="text-2xl font-bold text-green-900">{candidate.answers.length}</p>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl p-4 border border-purple-200">
              <div className="flex items-center gap-3">
                <div className="bg-purple-500 p-2 rounded-lg">
                  <Clock className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="text-sm text-purple-700 font-medium">Total Time</p>
                  <p className="text-2xl font-bold text-purple-900">{formatTime(totalTimeUsed)}</p>
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-orange-50 to-orange-100 rounded-xl p-4 border border-orange-200">
              <div className="flex items-center gap-3">
                <div className="bg-orange-500 p-2 rounded-lg">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="text-sm text-orange-700 font-medium">Avg Time</p>
                  <p className="text-2xl font-bold text-orange-900">{formatTime(avgTimePerQuestion)}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Performance Chart */}
          <div className="bg-gray-50 rounded-xl p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
              <BarChart3 className="w-5 h-5 text-indigo-600" />
              <h3 className="text-lg font-bold text-gray-800">Question-by-Question Performance</h3>
            </div>
            
            <div className="space-y-4">
              {candidate.answers.map((ans, idx) => {
                const maxScoreForQ = ans.difficulty === 'Easy' ? 10 : ans.difficulty === 'Medium' ? 20 : 30;
                const scorePercent = Math.round((ans.score / maxScoreForQ) * 100);
                
                return (
                  <div key={idx} className="bg-white rounded-lg p-4 border border-gray-200">
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="bg-indigo-100 text-indigo-700 text-xs font-bold px-2 py-1 rounded">
                          Q{idx + 1}
                        </span>
                        <span className={`text-xs font-semibold px-2 py-1 rounded ${
                          ans.difficulty === 'Easy' ? 'bg-green-100 text-green-700' :
                          ans.difficulty === 'Medium' ? 'bg-yellow-100 text-yellow-700' :
                          'bg-red-100 text-red-700'
                        }`}>
                          {ans.difficulty}
                        </span>
                      </div>
                      <div className="text-right">
                        <span className="text-lg font-bold text-indigo-600">{ans.score}/{maxScoreForQ}</span>
                        <span className="text-sm text-gray-500 ml-2">({scorePercent}%)</span>
                      </div>
                    </div>
                    
                    <p className="text-sm text-gray-700 mb-2 font-medium">{ans.question}</p>
                    
                    {/* Progress bar */}
                    <div className="w-full bg-gray-200 rounded-full h-2 mb-2">
                      <div 
                        className={`h-2 rounded-full transition-all ${
                          scorePercent >= 80 ? 'bg-green-500' :
                          scorePercent >= 60 ? 'bg-blue-500' :
                          scorePercent >= 40 ? 'bg-yellow-500' :
                          'bg-red-500'
                        }`}
                        style={{ width: `${scorePercent}%` }}
                      />
                    </div>
                    
                    {ans.feedback && (
                      <p className="text-xs text-gray-600 italic">💡 {ans.feedback}</p>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={handleDownloadReport}
              className="flex-1 bg-indigo-600 text-white px-6 py-3 rounded-xl hover:bg-indigo-700 transition font-semibold flex items-center justify-center gap-2"
            >
              <Download className="w-5 h-5" />
              Download Report
            </button>
            
            <button
              onClick={onViewDashboard}
              className="flex-1 bg-purple-600 text-white px-6 py-3 rounded-xl hover:bg-purple-700 transition font-semibold flex items-center justify-center gap-2"
            >
              <BarChart3 className="w-5 h-5" />
              View Dashboard
            </button>
            
            <button
              onClick={onClose}
              className="flex-1 bg-gray-200 text-gray-700 px-6 py-3 rounded-xl hover:bg-gray-300 transition font-semibold"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default InterviewReport;